version: '2'

services:
  app:
    command:  npm run start
    image: 'docker-phaser3-typescript'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/:/app
      - ./app/node_modules:/app/node_modules
    ports:
      - 8080:8080
